version: '3'

tasks:
  server:
    desc: Start API server
    cmds:
    - go run main.go

  db:
    desc: Start database
    cmds:
    - docker-compose up -d

  proto:
    dir: proto/
    desc: Generates protobuf golang services
    cmds:
    - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative *.proto
